---
- name: Sample Playbook
  hosts: all
  become: yes
  tasks:
    - name: Install Apache
      package:
        name: "{{ package }}""
        state: present
    - name: Enable & Start
      systemd_service:
        name: "{{ package }}""
        enabled: yes
        state: started
