---
- name: Sample Playbook
  hosts: all
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: {{ package }}
        state: present
      when: ansible_facts['os_family'] == 'Debian'
    - name: Install Apache
      dnf:
        name: {{ package }}
        state: present
      when: ansible_facts['os_family'] == 'RedHat'
    - name: Enable & Start
      systemd_service:
        name: httpd
        enabled: yes
        state: started
        