---
- name: Sample Playbook
  hosts: all
  become: yes
  tasks:
    - name: Install Apache
      ansible.builtin.shell:
        cmd: ls -l
      register: output
    - name: display output value
      debug:
        var: output
        