---
- name: Sample Playbook
  hosts: all
  become: yes
  tasks:
    - name: Install Git
      apt:
        name: git
        state: present
    - name: Install Nginx
      apt:
        name: nignx
        state: absent
    - name: Install Apache
      apt:
        name: apache2
        state: present
    - name: Enabling Apache
      service:
        name: apache2
        enabled: yes
    - name: Starting Apache
      service:
        name: apache2
        state: started